basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a simple boilerplate API.
  title: Boilerplate API
  version: "1.0"
paths:
  /users/{id}:
    delete:
      consumes:
      - application/json
      description: Delete an user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Delete an user
      tags:
      - users
    get:
      consumes:
      - application/json
      description: get user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Show an user
      tags:
      - users
    post:
      consumes:
      - application/json
      description: Add an user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Add an user
      tags:
      - users
    put:
      consumes:
      - application/json
      description: Update an user by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses: {}
      summary: Update an user
      tags:
      - users
swagger: "2.0"
